### ISSUE TITLE
为什么会死循环呢？

### ISSUE THREAD

**Issue by xhacker5000** [justan/lrc#5]
难道用法不对。永远出不去while
     timeExp.lastIndex = 0;
    for(var i = 0, l = lines.length; i < l; i++){
      while(time = timeExp.exec(lines[i])){
        line = Parser.trim(lines[i].replace(timeExp, ''));
        this.lines.push({
            time: time[1] * 60 * 1000 + time[2] * 1000 + (time[3] || 0) * 10
          , originLineNum: i
          , txt: line
        });
        this.txts.push(line);
      }
    }

**Comment by justan** [comment]
请参考
https://github.com/justan/lrc/commit/c4e9b563b389843e8e784c949ce55c9be3a3c3ed

**Comment by justan** [comment]
主干上的最新代码是没有问题的
https://github.com/justan/lrc/issues/1
